### ISSUE TITLE
Почему try тут?

### ISSUE THREAD

**Issue by boris-dev** [Bharbo/liga-internship#4]
https://github.com/Bharbo/liga-internship/blob/099d7d38a946e938bf52e7f195329e2cfe8b1bdd/MidiSong/src/main/java/ru/liga/song/logic/Reader.java#L21

Если не спарсится то, что нужно делать?

**Comment by Qunitellow** [comment]
Если не спарсится, то нужно выкинуть NumberFormatException. Да, я понял что не нужно прописывать для каждого кейса свой try...catch)
