### ISSUE TITLE
Почему возвращается лист листов?

### ISSUE THREAD

**Issue by boris-dev** [Bharbo/liga-internship#5]
https://github.com/Bharbo/liga-internship/blob/099d7d38a946e938bf52e7f195329e2cfe8b1bdd/MidiSong/src/main/java/ru/liga/song/logic/Analyze.java#L28

В коде я увидел только работу с одним листом.
И нарушение конвенции именования, почему через _ ? Так нельзя=) Только CamelCase

**Comment by Qunitellow** [comment]
Изначально думал что в мелодии может быть больше одного головой дорожки, поэтому и сделал лист листов. Исправил, т.к. в наших мелодиях по одной головой дорожке.
